name: BuildAndDeploy

on:
  push:
    branches: [master]

env:
  version: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and push to Docker
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: 'Dockerfile'
          IMAGE_NAME: 'k9wallet/k9wallet-website'
          TAG_NAME: ${{ env.version }}
          LATEST: 'true'
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@master
      - name: Deploy to cluster
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG }}
          args: set image deployment/k9wallet-website-deployment k9wallet-website=k9wallet/k9wallet-website:${{ env.version }} --record
      - name: Verify deployment
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG }}
          args: '"rollout status deployment/k9wallet-website-deployment"'
